/** Real neighborhood photos from Wikimedia Commons. CC licenses require the credit to be shown wherever the photo is used. */
export type AreaPhoto = { src: string; credit: string; license: string; licenseUrl: string; source: string };

export const AREA_PHOTOS: Record<string, AreaPhoto> = {
  "Downtown": { src: "/photos/_areas/downtown.jpg", credit: "Bulliver", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/", source: "https://commons.wikimedia.org/wiki/File:Edmonton_Downtown_Skyline_daytime_new.jpg" },
  "Whyte Ave": { src: "/photos/_areas/whyte-ave.jpg", credit: "TagaSanPedroAko", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", source: "https://commons.wikimedia.org/wiki/File:Whyte_Avenue_at_104_Street_01_11-04-2022.jpg" },
  "Jasper Ave": { src: "/photos/_areas/jasper-ave.jpg", credit: "TagaSanPedroAko", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", source: "https://commons.wikimedia.org/wiki/File:Jasper_Avenue_and_101_Street_at_dusk,_11-16-2023.jpg" },
  "124 Street": { src: "/photos/_areas/124-street.jpg", credit: "WinterE229 WinterforceMedia", license: "Public domain", licenseUrl: "", source: "https://commons.wikimedia.org/wiki/File:North_Saskatchewan_River_Valley_Edmonton_Alberta_Canada_01A.jpg" },
  "West Edmonton": { src: "/photos/_areas/west-edmonton.jpg", credit: "TagaSanPedroAko", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", source: "https://commons.wikimedia.org/wiki/File:WEM_Phase_III_at_Deep_Sea_Adventure_Lake_03-25-2023.jpg" },
  "South Edmonton": { src: "/photos/_areas/south-edmonton.jpg", credit: "Joli Rumi", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", source: "https://commons.wikimedia.org/wiki/File:Whitemud_Creek_park,_Edmonton,_Alberta3.jpg" },
  "Mill Woods": { src: "/photos/_areas/mill-woods.jpg", credit: "Mack Male", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", source: "https://commons.wikimedia.org/wiki/File:Canada_Day_in_Mill_Woods_(27792826930).jpg" },
  "Windermere": { src: "/photos/_areas/windermere.jpg", credit: "Kamakou", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", source: "https://commons.wikimedia.org/wiki/File:Edmonton,_Mid_Autumn_Terwillegar_Park.jpg" },
  "Sherwood Park": { src: "/photos/_areas/sherwood-park.jpg", credit: "Thankyoubaby", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/", source: "https://commons.wikimedia.org/wiki/File:Sherwood_Park.jpg" },
  "St. Albert": { src: "/photos/_areas/st-albert.jpg", credit: "Erik Lizee", license: "Public domain", licenseUrl: "", source: "https://commons.wikimedia.org/wiki/File:Sturgeonriverstalbert.jpg" },
  "Spruce Grove": { src: "/photos/_areas/spruce-grove.jpg", credit: "TagaSanPedroAko", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", source: "https://commons.wikimedia.org/wiki/File:Northern_Lights_over_Spruce_Grove_2021-11-4_0220.jpg" },
  "North Edmonton": { src: "/photos/_areas/north-edmonton.jpg", credit: "Quintin Soloviev", license: "CC BY 4.0", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", source: "https://commons.wikimedia.org/wiki/File:Commonwealth_Stadium,_Edmonton,_AB.jpg" },
  "Beverly": { src: "/photos/_areas/beverly.jpg", credit: "Mack Male", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", source: "https://commons.wikimedia.org/wiki/File:Beverly_(19354503558).jpg" },
  "Castle Downs": { src: "/photos/_areas/castle-downs.jpg", credit: "dfaulder", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", source: "https://commons.wikimedia.org/wiki/File:Common_Loons_on_Beaumaris_Lake_(8696976751).jpg" },
  "Beaumont": { src: "/photos/_areas/beaumont.jpg", credit: "WinterE229 WinterforceMedia", license: "Public domain", licenseUrl: "", source: "https://commons.wikimedia.org/wiki/File:Saint_Vital_Roman_Catholic_Church_Beaumont_Alberta_Canada_01A.jpg" },
};
