export const SITE = {
  name: "WhereToYEG",
  domain: "wheretoyeg.ca",
  url: "https://wheretoyeg.ca",
  tagline: "Find the good stuff.",
  description:
    "Edmonton's local business directory. Discover the best restaurants, barbers, cafes, and hidden gems across YEG.",
  email: "info@onepointsolutionsca.com",
  social: {
    instagram: "https://instagram.com/wheretoyeg",
    tiktok: "https://tiktok.com/@wheretoyeg",
  },
  neighborhoods: [
    "Downtown",
    "Whyte Ave",
    "Jasper Ave",
    "West Edmonton",
    "South Edmonton",
    "Mill Woods",
    "Windermere",
    "Sherwood Park",
    "St. Albert",
    "Spruce Grove",
    "North Edmonton",
    "Beverly",
    "Castle Downs",
    "Beaumont",
  ],
  popularSearches: [
    { label: "Halal Food", href: "/restaurants?amenity=Halal" },
    { label: "Barbers", href: "/barbers" },
    { label: "Lash Techs", href: "/lash-techs" },
    { label: "Coffee Shops", href: "/cafes-coffee-shops" },
    { label: "Walk-in Clinics", href: "/medical/walk-in-clinics" },
    { label: "Nail Salons", href: "/nail-salons" },
    { label: "Bakeries", href: "/bakeries" },
    { label: "Gyms", href: "/gyms-fitness" },
  ],
};
